### ISSUE TITLE
`readinessProbe` and `livenessProbe` timeout too short

### ISSUE THREAD

**Issue by towolf** [google-cloud-tools/kube-eagle-helm-chart#2]
```
time curl 172.31.0.85:8080/health
Ok
real    0m1,429s
user    0m0,008s
sys     0m0,011s
```

It's taking longer than the default 1s to return the /health endpoint.

**Comment by VidhiG** [comment]
@weeco what should be the ideal timeout value. I had updated it to 30s but the kube-eagle pod is still restarting frequently.
