### ISSUE TITLE
kube-eagle pod is restarting frequently

### ISSUE THREAD

**Issue by vidhig** [google-cloud-tools/kube-eagle-helm-chart#4]
the kube-eagle pod is restarting frequently. 
This is the error I got.
```
panic: the server is currently unable to handle the request (get pods.metrics.k8s.io)

goroutine 38 [running]:
github.com/google-cloud-tools/kube-eagle/vendor/github.com/weeco/kube-eagle/pkg/metrics_store.Collect()
	/go/src/github.com/google-cloud-tools/kube-eagle/vendor/github.com/weeco/kube-eagle/pkg/metrics_store/metrics_store.go:59 +0x386
main.main.func1()
	/go/src/github.com/google-cloud-tools/kube-eagle/main.go:56 +0x32
created by main.main
	/go/src/github.com/google-cloud-tools/kube-eagle/main.go:52 +0x47
```

**Comment by weeco** [comment]
Apparently it cannot get the pod list from the kubernetes master. Do you get a response for `kubectl get pods --all-namespaces -o wide`?

Also please make sure you are using kube eagle v 1.1.0, it seems you are using version 1.0.0 which was until recently the default in this helm chart.

**Comment by weeco** [comment]
I'll close this issue due too inactivity.
